// import { API } from '@/utils/api';
import type { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'Optimized Closets',
  description: 'Generated by create next app',
};
const env = process.env.NODE_ENV;
export default async function Page() {
  // const api = new API();
  // const jumbos = await api.get(`jumbo/find-main`, {
  //   next: { revalidate: env === 'development' ? 10 : 3600 },
  // });
  return (
    <>
      <section></section>
    </>
  );
}
